#!/usr/bin/env bash
# wave-2-luna-codex.sh — GPT-5.6 Luna through Codex, on the OpenAI subscription.
# One command, no arguments. Running it IS the approval for this batch's spend.
#
#   taskbench/launch/wave-2-luna-codex.sh
#
# Two facts this arm records that the others do not have to:
#
#   * **Codex reports no server-resolved model id.** Its event stream echoes nothing about
#     which model answered. The record therefore carries the requested string and an explicit
#     note that no resolved identity was available — the launch alias is not promoted into one.
#   * **Its harness state and its credential live in the same directory.** `cell-codex.sh`
#     builds a per-cell `CODEX_HOME` holding a copy of `auth.json` and nothing else, so prior
#     threads, memories, goals, queues, skills and plugins are absent rather than disabled.
#
# Luna unreachable is the HIP's recorded W2 result, not a benchmark failure. If this arm cannot
# authenticate, that is recorded as `unreachable` with the failure boundary named — it is never
# rerouted through another provider or harness, and never scored as a model failure.

set -euo pipefail

# shellcheck source=taskbench/launch/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

readonly RECORD_BASE="wave-2-luna-codex"
readonly MODEL="gpt-5.6-luna"
readonly VENDOR="openai"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly REPO_ROOT
readonly RECORDS_DIR="$REPO_ROOT/taskbench/records"
readonly WORK_BASE="${TASKBENCH_WORK_BASE:-$HOME/work/taskbench}"
readonly CELL_WRAPPER="$REPO_ROOT/taskbench/launch/cell-codex.sh"
readonly CODEX_AUTH="$HOME/.codex/auth.json"

step "The bundle under test"
need codex  "this arm's harness"
need claude "the blinded reviewer is a Claude Code session, identical across every bundle"
need uv     "taskbench runs under uv"
need bwrap  "the reviewer's cold-reader sandbox needs it"
need git    "the materializer exports pre-task trees with it"

[ -x "$CELL_WRAPPER" ] || die "$CELL_WRAPPER is missing or not executable"
[ -f "$CODEX_AUTH" ] || die "no Codex credential at $CODEX_AUTH.

  The ChatGPT subscription login is an operator act. Complete it, then re-run:

      codex login

  This launcher copies the credential into each disposable cell home; it never creates one,
  and it never reads or prints its contents."

HARNESS_VERSION="$(codex_harness_version)"
readonly HARNESS_VERSION

say "vendor:   $VENDOR"
say "model:    $MODEL   (requested; Codex reports no server-resolved id, and the record says so)"
say "harness:  $HARNESS_VERSION"
say "gateway:  none — the ChatGPT subscription, direct"
say "state:    a fresh CODEX_HOME per cell, carrying auth.json and nothing else"

step "Reserving a record"
read -r RECORD_ID SUPERSEDES <<<"$(reserve_record "$REPO_ROOT" "$RECORD_BASE" "$RECORDS_DIR")"
readonly RECORD_ID SUPERSEDES
WORK_ROOT="$WORK_BASE/$RECORD_ID"
readonly WORK_ROOT
say "record:   $RECORD_ID"
[ "$SUPERSEDES" != "-" ] && say "NOTE:     supersedes $SUPERSEDES, kept unmodified."
read -r RESUME_FROM RESUME_COUNT <<<"$(resume_target "$REPO_ROOT" "$RECORD_BASE" "$RECORDS_DIR")"
readonly RESUME_FROM RESUME_COUNT
[ "$RESUME_FROM" != "-" ] && \
  say "resume:   carrying $RESUME_COUNT conclusive cell(s) from $(basename "$RESUME_FROM")"
say "work:     $WORK_ROOT"
mkdir -p "$WORK_ROOT" "$RECORDS_DIR"

step "Generating the runner config"
CONFIG="$WORK_ROOT/runner-config.yaml"
readonly CONFIG
{
  printf '# Generated by wave-2-luna-codex.sh — do not hand-edit.\n'
  printf 'agent:\n'
  # `-s workspace-write` keeps Codex inside the cell it was given. `--ephemeral` is deliberately
  # NOT used: the rollout file it would suppress is the only place Codex records the model
  # string it ran with, and this arm is already short one identity surface.
  # No `-C`: the runner already launches the process with cwd=<cell>/code (the `cwd: code`
  # below), so a `-C code` on top of that resolves to <cell>/code/code, which does not exist.
  printf '  argv: ["%s", "-m", "%s", "-s", "workspace-write"]\n' \
         "$CELL_WRAPPER" "$MODEL"
  printf '  labels: {vendor: "%s", model: "%s", harness: "%s"}\n' \
         "$VENDOR" "$MODEL" "$HARNESS_VERSION"
  printf '  result_envelope: codex-jsonl\n'
  printf '  env_passthrough: ["PATH", "LANG", "TERM", "XDG_RUNTIME_DIR"]\n'
  printf '  env:\n'
  printf '    CODEX_AUTH_SOURCE: "%s"\n' "$CODEX_AUTH"
  printf '    GIT_TERMINAL_PROMPT: "0"\n'
  printf '  cwd: code\n'
  printf '  timeout_s: 7200\n'
  printf '  prompt_mode: argv\n'
  emit_reviewer_block
  emit_sources_block "$REPO_ROOT"
} > "$CONFIG"
say "config:   $CONFIG"

step "Smoke: one disposable read/edit/test loop on this exact bundle"
say "Same argv the batch will use, against a three-file fixture. A bundle that cannot read a"
say "file it was not given, edit a second and run the third has nothing to say about an order."
set +e
(
  cd "$REPO_ROOT" || exit 1
  uv run --frozen taskbench qualify-smoke \
    --config "$CONFIG" --bundle "luna-codex" \
    --root "$WORK_ROOT/smoke" --out "$WORK_ROOT"
)
smoke_status=$?
set -e
if [ "$smoke_status" -ne 0 ]; then
  say ""
  say "The batch does NOT run. Nothing was scored and nothing was spent on the matrix."
  exit "$smoke_status"
fi

install_interrupt_trap "$RECORDS_DIR" "$RECORD_ID" "$WORK_ROOT"

step "The pause point: $FIRST_TASK first"
say "Same fixed order as every other bundle. Stop and look when it finishes."

set +e
(
  cd "$REPO_ROOT" || exit 1
  args=(
    --config "$CONFIG" --record-id "$RECORD_ID" --work-root "$WORK_ROOT"
    --out "$RECORDS_DIR" --expect-corpus-hash "$EXPECT_CORPUS_HASH"
    --tasks "$FIRST_TASK,instrument-teeth,launch-pane-fix,ptc-revalidate,run-registration"
  )
  [ "$SUPERSEDES" != "-" ] && args+=(--supersedes "$SUPERSEDES")
  [ "$RESUME_FROM" != "-" ] && args+=(--resume-from "$RESUME_FROM")
  uv run --frozen taskbench run "${args[@]}"
)
status=$?
set -e

report_status "$status" "$RECORDS_DIR/$(date +%F)-$RECORD_ID" "$WORK_ROOT" "$REPO_ROOT"
exit "$status"
