#!/usr/bin/env bash
# Deployment checks 1–5 (deployment spec §7 step 5 / test plan T1 core), fully
# containerized — a scripted, cognition-free harness runnable against a fresh
# `compose up`. Hard-fails on any check. Re-run on any environment change (§5).
#
# Isolation: the harness drives its **own** per-run spine database (tests/scratch_db.py,
# the same mechanism the pytest paths use), created here and dropped on exit. Concurrent
# runs therefore never race on one spine — check 1 seeds and folds it, check 3 dumps and
# restores it, and the structural checks write a fixed probe run into it, all of which
# collided while that spine was shared. It also keeps the harness out of the durable
# `omegahive` database, which it used to seed `checks-*` runs into and pg_dump wholesale.
#
# Preconditions: an OCI runtime + compose v2 (DOCKER_HOST set for rootless Podman);
# the omegahive image built; Postgres up. Migrations run here, on the scratch spine.
set -euo pipefail
cd "$(dirname "$0")/.."

: "${DOCKER_HOST:=unix://${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/podman/podman.sock}"
export DOCKER_HOST

if docker compose version >/dev/null 2>&1; then DC=(docker compose); else DC=(docker-compose); fi
FILES=()
dc() { "${DC[@]}" ${FILES[@]+"${FILES[@]}"} "$@"; }

RUN="checks-$(date +%s)"
export OMEGAHIVE_RUN_ID="$RUN"
PASS=0; FAIL=0
ok()  { echo "[PASS] $1"; PASS=$((PASS+1)); }
bad() { echo "[FAIL] $1"; FAIL=$((FAIL+1)); }

# --- this run's own spine ---------------------------------------------------
# `scratch_db.py new` creates the database and prints "<name> <DSN>" — both, so nothing here
# has to parse a database name out of a URL (a base DSN carrying `?sslmode=…` defeats a naive
# `${url##*/}`, and the mangled name would then leak instead of being dropped). The name
# carries an epoch, so a run killed before the trap below leaves an orphan that the next
# suite's age-based sweep reaps (or `scratch_db.py sweep` does — see the README).
SPINE_DB=""; RESTORE_DB=""; OVERRIDE=""
cleanup() {
  status=$?
  FILES=()   # the drops are plain-compose work, and the override is about to go away
  for db in "$RESTORE_DB" "$SPINE_DB"; do
    [ -n "$db" ] || continue
    dc run --rm -T --entrypoint python cli /app/tests/scratch_db.py drop "$db" \
       >/dev/null 2>&1 || echo "warning: could not drop $db — sweep it later" >&2
  done
  [ -z "$OVERRIDE" ] || rm -f "$OVERRIDE"
  exit "$status"
}
trap cleanup EXIT   # installed before the database exists, so nothing can leak past it

ERRLOG="$(mktemp -t omegahive-checks-err-XXXXXX)"
# `|| true`: under `set -e` a failing command substitution aborts at the assignment, which
# would make the guard below unreachable and the failure completely silent.
SPINE_OUT="$(dc run --rm -T --entrypoint python cli /app/tests/scratch_db.py new \
             2>"$ERRLOG" | tr -d '\r' | tail -1)" || true
read -r SPINE_DB SPINE_URL <<<"$SPINE_OUT" || true
case "${SPINE_URL:-}" in
  postgres*://*/*) rm -f "$ERRLOG" ;;
  *) echo "could not create the scratch spine database; compose said:" >&2
     sed 's/^/  /' "$ERRLOG" >&2; rm -f "$ERRLOG"
     SPINE_DB=""   # nothing was created, so leave the trap nothing to drop
     exit 1 ;;
esac
RESTORE_DB="${SPINE_DB}_restore"
RESTORE_URL="$(dc run --rm -T --entrypoint python cli /app/tests/scratch_db.py url \
               "$RESTORE_DB" 2>/dev/null | tr -d '\r' | tail -1)"

OVERRIDE="$(mktemp -t omegahive-checks-XXXXXX.yml)"
# `environment:` wins over `env_file:`, so this redirects every service the harness drives
# onto the scratch spine while `.env` keeps pointing the real stack at the durable one.
# `$` is doubled: compose interpolates this file, so a password containing `$` would
# otherwise be silently mangled or expanded from the host environment.
esc() { printf '%s' "$1" | sed 's/\$/$$/g'; }
{
  echo "# generated by scripts/deploy_checks.sh — transient, removed with the run"
  echo "services:"
  for svc in migrate seed coordinator worker review board-view deploy-checks; do
    printf '  %s:\n    environment:\n      OMEGAHIVE_DATABASE_URL: "%s"\n' \
      "$svc" "$(esc "$SPINE_URL")"
  done
  printf '  backup:\n    environment:\n      OMEGAHIVE_DATABASE_URL: "%s"\n      OMEGAHIVE_RESTORE_DB: "%s"\n' \
    "$(esc "$SPINE_URL")" "$RESTORE_DB"
} > "$OVERRIDE"
FILES=(-f docker-compose.yml -f "$OVERRIDE")

echo "== deployment checks (run=$RUN, spine=$SPINE_DB) =="

# 0. the scratch spine starts empty — apply the schema before anything reads it. Reported,
# not swallowed: every check below reads this schema, so a silent failure here would surface
# as four unrelated-looking check failures.
if ! MIGRATE0="$(dc run --rm migrate 2>&1)"; then
  echo "could not apply migrations to the scratch spine:" >&2
  sed 's/^/  /' <<<"$MIGRATE0" >&2
  exit 1
fi

# 1. acceptance — the multi-process run reaches the expected terminal board state.
dc run --rm seed >/dev/null 2>&1
dc up --abort-on-container-exit coordinator worker review >/dev/null 2>&1 || true
BOARD="$(dc run --rm board-view 2>/dev/null || true)"
if [ "$(grep -c 'done' <<<"$BOARD")" -ge 2 ]; then
  ok "1. acceptance: board terminal (t1,t2 done)"
else
  bad "1. acceptance: board not terminal"; echo "$BOARD"
fi

# 2. migration idempotence — a second migrate is a no-op.
M="$(dc run --rm migrate 2>/dev/null || true)"
if grep -qi 'no pending migrations' <<<"$M"; then
  ok "2. migration idempotence: second run is a no-op"
else
  bad "2. migration idempotence: unexpected output: $M"
fi

# 3. snapshot + restore — the replayed log is byte-identical (event-level equality).
dc run --rm --entrypoint sh backup /scripts/pg_restore_check.sh >/dev/null 2>&1
LIVE="$(dc run --rm board-view report "$RUN" --json 2>/dev/null || true)"
REST="$(dc run --rm -e OMEGAHIVE_DATABASE_URL="$RESTORE_URL" board-view report "$RUN" --json 2>/dev/null || true)"
if [ -n "$LIVE" ] && [ "$LIVE" = "$REST" ]; then
  ok "3. snapshot+restore: replayed log identical"
else
  bad "3. snapshot+restore: logs differ"
fi

# 4 & 5. structural — tier-routing (no ungoverned route) + credential scope. Hard-fail.
if dc run --rm deploy-checks 2>/dev/null; then
  ok "4-5. structural checks (tier-routing, credential scope)"
else
  bad "4-5. structural checks"
fi

echo "== $PASS passed, $FAIL failed =="
[ "$FAIL" -eq 0 ]
