#!/usr/bin/env python3
"""Render the versioned JSON API's Pydantic response models to
`docs/reference/omegahive_api_schema.md` (hive-mcp order, scope item 4: "publish
their JSON schemas in the code documentation").

Run after any change to `omegahive.api.models`:

    uv run python scripts/emit_api_schemas.py

The check target (`--check`) fails if the committed doc is stale — wired into CI
alongside ruff/mypy so the published schema can never drift from the code.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from omegahive.api import models  # noqa: E402

_DOC = Path(__file__).resolve().parents[1] / "docs" / "reference" / "omegahive_api_schema.md"

_RESPONSE_MODELS = [
    models.HealthResponse,
    models.PortfolioResponse,
    models.TaskDetailResponse,
    models.ErrorResponse,
]


def render() -> str:
    lines = [
        "# OmegaHive versioned JSON API — response schemas",
        "",
        f"**Generated by `scripts/emit_api_schemas.py`. Do not hand-edit.** "
        f"Schema version `{models.API_SCHEMA_VERSION}`.",
        "",
        "Source of truth: `src/omegahive/api/models.py`. Regenerate after any change:",
        "",
        "```sh",
        "uv run python scripts/emit_api_schemas.py",
        "```",
        "",
        "Routes: `GET /api/v1/health` -> `HealthResponse`; "
        "`GET /api/v1/portfolio` -> `PortfolioResponse`; "
        "`GET /api/v1/runs/{run_id}/tasks/{task_id}` -> `TaskDetailResponse`. "
        "Every non-2xx response on every route is `ErrorResponse`.",
        "",
    ]
    for model in _RESPONSE_MODELS:
        schema = model.model_json_schema()
        lines.append(f"## `{model.__name__}`")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(schema, indent=2, sort_keys=True))
        lines.append("```")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    rendered = render()
    if "--check" in sys.argv[1:]:
        current = _DOC.read_text() if _DOC.exists() else ""
        if current != rendered:
            print(f"stale: {_DOC} does not match omegahive.api.models — regenerate it")
            return 1
        print("up to date")
        return 0
    _DOC.write_text(rendered)
    print(f"wrote {_DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
